/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria a conta da igreja e retorna um token já autenticado (conta ativa imediatamente, sem confirmação de e-mail) */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica a igreja e retorna o token de acesso; rememberMe define a expiração (24h ou 30 dias) */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia a recuperação de senha: gera token de uso único (1h), invalida o anterior e envia o link por e-mail */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Define a nova senha a partir do token recebido por e-mail */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os membros da igreja, paginado e com busca por nome */
        get: operations["MembersController_findAll"];
        put?: never;
        /** Cadastra um novo membro */
        post: operations["MembersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca um membro pelo id */
        get: operations["MembersController_findOne"];
        put?: never;
        post?: never;
        /** Remove um membro (soft delete) */
        delete: operations["MembersController_remove"];
        options?: never;
        head?: never;
        /** Atualiza os dados de um membro */
        patch: operations["MembersController_update"];
        trace?: never;
    };
    "/v1/ministries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os ministérios da igreja, paginado e com busca por nome */
        get: operations["MinistriesController_findAll"];
        put?: never;
        /** Cadastra um novo ministério */
        post: operations["MinistriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ministries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca um ministério pelo id */
        get: operations["MinistriesController_findOne"];
        put?: never;
        post?: never;
        /** Remove um ministério (soft delete) */
        delete: operations["MinistriesController_remove"];
        options?: never;
        head?: never;
        /** Atualiza os dados de um ministério */
        patch: operations["MinistriesController_update"];
        trace?: never;
    };
    "/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna o perfil da igreja autenticada */
        get: operations["AccountController_getProfile"];
        put?: never;
        post?: never;
        /** Exclui a conta da igreja (soft delete, irreversível, acesso revogado imediatamente) */
        delete: operations["AccountController_deleteAccount"];
        options?: never;
        head?: never;
        /** Atualiza o perfil da igreja (cnpj e denomination só podem ser preenchidos aqui) */
        patch: operations["AccountController_updateProfile"];
        trace?: never;
    };
    "/v1/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Altera a senha da conta, exigindo a senha atual */
        patch: operations["AccountController_changePassword"];
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as categorias de transação da igreja, com filtro por tipo e paginação */
        get: operations["CategoriesController_findAll"];
        put?: never;
        /** Cria uma nova categoria (o tipo é imutável após a criação) */
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove uma categoria (soft delete), permitido mesmo com transações vinculadas */
        delete: operations["CategoriesController_remove"];
        options?: never;
        head?: never;
        /** Atualiza parcialmente uma categoria existente (exceto o tipo) */
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as transações da igreja, com busca, filtros e paginação */
        get: operations["TransactionsController_findAll"];
        put?: never;
        /** Cadastra uma nova transação */
        post: operations["TransactionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca uma transação pelo id */
        get: operations["TransactionsController_findOne"];
        put?: never;
        post?: never;
        /** Remove uma transação (soft delete) */
        delete: operations["TransactionsController_remove"];
        options?: never;
        head?: never;
        /** Atualiza os dados de uma transação */
        patch: operations["TransactionsController_update"];
        trace?: never;
    };
    "/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cards de métrica (Saldo, Entradas, Saídas, Balanço) e métricas extras da tela Dashboard */
        get: operations["DashboardController_getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gráfico de linha (entradas/saídas ao longo do tempo) e pizzas de entradas/saídas por categoria */
        get: operations["DashboardController_getCharts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description Nome da igreja
             * @example Igreja Batista Central
             */
            name: string;
            /**
             * Format: email
             * @description E-mail, usado como login
             * @example contato@igrejacentral.com.br
             */
            email: string;
            /**
             * @description Telefone de contato
             * @example (11) 99999-0000
             */
            phone?: string;
            /**
             * @description Mínimo de 8 caracteres, sem regra especial de composição
             * @example senhaSegura123
             */
            password: string;
        };
        LoginDto: {
            /**
             * Format: email
             * @description E-mail cadastrado
             * @example contato@igrejacentral.com.br
             */
            email: string;
            /**
             * @description Senha da conta
             * @example senhaSegura123
             */
            password: string;
            /**
             * @description Se true, o token expira em 30 dias em vez de 24h
             * @default false
             */
            rememberMe: boolean;
        };
        ForgotPasswordDto: {
            /**
             * Format: email
             * @description E-mail da conta a recuperar
             * @example contato@igrejacentral.com.br
             */
            email: string;
        };
        ResetPasswordDto: {
            /** @description Token recebido por e-mail */
            token: string;
            /**
             * @description Nova senha — mínimo de 8 caracteres
             * @example novaSenhaSegura456
             */
            newPassword: string;
        };
        CreateMemberDto: {
            /**
             * @description Nome do membro
             * @example João da Silva
             */
            name: string;
            /**
             * @description Data de nascimento (ISO 8601)
             * @example 1990-05-20
             */
            birthDate?: string;
            /**
             * @description Data de batismo (ISO 8601)
             * @example 2010-12-01
             */
            baptismDate?: string;
            /**
             * Format: email
             * @description E-mail de contato
             * @example joao@exemplo.com
             */
            email?: string;
            /**
             * @description Telefone de contato
             * @example (11) 99999-0000
             */
            phone?: string;
        };
        UpdateMemberDto: {
            /**
             * @description Nome do membro
             * @example João da Silva
             */
            name?: string;
            /**
             * @description Data de nascimento (ISO 8601)
             * @example 1990-05-20
             */
            birthDate?: string;
            /**
             * @description Data de batismo (ISO 8601)
             * @example 2010-12-01
             */
            baptismDate?: string;
            /**
             * Format: email
             * @description E-mail de contato
             * @example joao@exemplo.com
             */
            email?: string;
            /**
             * @description Telefone de contato
             * @example (11) 99999-0000
             */
            phone?: string;
        };
        CreateMinistryDto: {
            /**
             * @description Nome do ministério
             * @example Ministério de Louvor
             */
            name: string;
            /**
             * @description Descrição do ministério
             * @example Ministério responsável pelo louvor e adoração.
             */
            description?: string;
            /**
             * Format: uuid
             * @description Id do membro responsável pelo ministério
             * @example 111e4567-e89b-12d3-a456-426614174000
             */
            responsibleId?: string;
        };
        UpdateMinistryDto: {
            /**
             * @description Nome do ministério
             * @example Ministério de Louvor
             */
            name?: string;
            /**
             * @description Descrição do ministério
             * @example Ministério responsável pelo louvor e adoração.
             */
            description?: string;
            /**
             * Format: uuid
             * @description Id do membro responsável pelo ministério
             * @example 111e4567-e89b-12d3-a456-426614174000
             */
            responsibleId?: string;
        };
        UpdateAccountDto: {
            /**
             * @description Nome da igreja
             * @example Igreja Batista Central
             */
            name?: string;
            /**
             * Format: email
             * @description E-mail de login
             * @example contato@igrejacentral.com.br
             */
            email?: string;
            /**
             * @description Telefone de contato
             * @example 11999999999
             */
            phone?: string;
            /**
             * @description CNPJ, validado com dígito verificador brasileiro — só preenchível aqui, não no cadastro
             * @example 11.444.777/0001-61
             */
            cnpj?: string;
            /**
             * @description Denominação — só preenchível aqui, não no cadastro
             * @example Batista
             */
            denomination?: string;
        };
        ChangePasswordDto: {
            /** @description Senha atual, para confirmação */
            currentPassword: string;
            /**
             * @description Nova senha — mínimo de 8 caracteres
             * @example novaSenhaSegura456
             */
            newPassword: string;
        };
        DeleteAccountDto: {
            /** @description Senha atual, para confirmação */
            currentPassword: string;
            /**
             * @description Frase de confirmação exibida na tela
             * @example EXCLUIR
             */
            confirmationPhrase: string;
        };
        CreateCategoryDto: {
            /**
             * @description Nome da categoria
             * @example Dízimo
             */
            name: string;
            /**
             * @description Descrição da categoria
             * @example Dízimo mensal dos membros
             */
            description?: string;
            /**
             * @description Tipo da categoria — imutável após a criação
             * @example income
             * @enum {string}
             */
            type: "income" | "expense";
            /**
             * @description Cor usada nos gráficos (hexadecimal)
             * @example #22C55E
             */
            color: string;
        };
        UpdateCategoryDto: {
            /**
             * @description Nome da categoria
             * @example Dízimo
             */
            name?: string;
            /**
             * @description Descrição da categoria
             * @example Dízimo mensal dos membros
             */
            description?: string;
            /**
             * @description Tipo da categoria — imutável após a criação
             * @example income
             * @enum {string}
             */
            type?: "income" | "expense";
            /**
             * @description Cor usada nos gráficos (hexadecimal)
             * @example #22C55E
             */
            color?: string;
        };
        CreateTransactionDto: {
            /**
             * @description Tipo da transação
             * @example income
             * @enum {string}
             */
            type: "income" | "expense";
            /**
             * @description Valor positivo (magnitude); o sinal é definido pelo type
             * @example 500
             */
            value: number;
            /**
             * @description Data da transação (ISO 8601)
             * @example 2026-07-01
             */
            date: string;
            /**
             * Format: uuid
             * @description Categoria da transação — deve ter o mesmo type
             * @example d3a8e1d2-0b4c-4d5f-9e1c-3a4b5c6d7e8f
             */
            categoryId: string;
            /**
             * @description Descrição livre
             * @example Dízimo do mês
             */
            description?: string;
            /**
             * Format: uuid
             * @description Id do membro vinculado
             * @example b1e6c9b0-8f2a-4b3e-9c9a-1e2f3a4b5c6d
             */
            memberId?: string;
            /**
             * Format: uuid
             * @description Id do ministério vinculado
             * @example 111e4567-e89b-12d3-a456-426614174000
             */
            ministryId?: string;
        };
        UpdateTransactionDto: {
            /**
             * @description Tipo da transação
             * @enum {string}
             */
            type?: "income" | "expense";
            /**
             * @description Valor positivo (magnitude); o sinal é definido pelo type
             * @example 550
             */
            value?: number;
            /**
             * @description Data da transação (ISO 8601)
             * @example 2026-07-01
             */
            date?: string;
            /**
             * Format: uuid
             * @description Categoria da transação — deve ter o mesmo type
             * @example d3a8e1d2-0b4c-4d5f-9e1c-3a4b5c6d7e8f
             */
            categoryId?: string;
            /**
             * @description Descrição livre; envie null para limpar
             * @example Dízimo do mês (ajustado)
             */
            description?: string | null;
            /**
             * Format: uuid
             * @description Id do membro vinculado; envie null para remover o vínculo
             */
            memberId?: string | null;
            /**
             * Format: uuid
             * @description Id do ministério vinculado; envie null para remover o vínculo
             */
            ministryId?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Conta criada; retorna token e dados da igreja. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Retorna token e expiresAt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description INVALID_CREDENTIALS — e-mail ou senha incorretos. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description Resposta genérica idêntica exista ou não a conta (não vaza e-mails cadastrados). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description Senha alterada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_findAll: {
        parameters: {
            query?: {
                /** @description Página (1-based) */
                page?: number;
                /** @description Itens por página */
                limit?: number;
                /** @description Busca por nome (contains, case-insensitive) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    MembersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MinistriesController_findAll: {
        parameters: {
            query?: {
                /** @description Página (1-based) */
                page?: number;
                /** @description Itens por página */
                limit?: number;
                /** @description Busca por nome (contains, case-insensitive) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MinistriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMinistryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MinistriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MinistriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MinistriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMinistryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccountController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccountController_deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccountController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AccountController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_findAll: {
        parameters: {
            query?: {
                /** @description Página (1-based) */
                page?: number;
                /** @description Itens por página */
                limit?: number;
                /** @description Filtra por tipo. Se omitido, retorna categorias de ambos os tipos. */
                type?: "income" | "expense";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_findAll: {
        parameters: {
            query?: {
                /** @description Página (1-based) */
                page?: number;
                /** @description Itens por página */
                limit?: number;
                /** @description Busca na descrição (contains, case-insensitive) */
                search?: string;
                /** @description Data inicial do período (ISO 8601) */
                dateFrom?: string;
                /** @description Data final do período (ISO 8601) */
                dateTo?: string;
                /** @description Filtra por categoria */
                categoryId?: string;
                /** @description Filtra por tipo; se omitido, retorna ambos */
                type?: "income" | "expense";
                /** @description Campo de ordenação; prefixo "-" para decrescente */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TransactionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getSummary: {
        parameters: {
            query?: {
                period?: "currentMonth" | "last3Months" | "last6Months" | "last12Months" | "currentYear" | "custom";
                /** @description Início do intervalo (obrigatório se period=custom) */
                dateFrom?: string;
                /** @description Fim do intervalo (obrigatório se period=custom) */
                dateTo?: string;
                /** @description uuids de categorias separados por vírgula */
                categoryIds?: string[];
                type?: "all" | "income" | "expense";
                /** @description Filtra por um ministério (oculta transações sem vínculo) */
                ministryId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getCharts: {
        parameters: {
            query?: {
                period?: "currentMonth" | "last3Months" | "last6Months" | "last12Months" | "currentYear" | "custom";
                /** @description Início do intervalo (obrigatório se period=custom) */
                dateFrom?: string;
                /** @description Fim do intervalo (obrigatório se period=custom) */
                dateTo?: string;
                /** @description uuids de categorias separados por vírgula */
                categoryIds?: string[];
                type?: "all" | "income" | "expense";
                /** @description Filtra por um ministério (oculta transações sem vínculo) */
                ministryId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
